# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81dc4c1fa88ed3c3236bb4ef39f13001ba4dfcb5535883655d6ecee257643288d321710a640d5d1c5cc37d71c1e635d28c08660a0ac5d7ddf77c021c8bfff556

test:
  secret_key_base: 778e11b123c6e9ad8f11eeb3132cddfd81b408356f19cb78f2b2d44b341fd61b7b7c282792ec8e5c4efea45e64ce5db7f8a4448d25f42b174e4fbed2f62d8851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
